let canvas, ctx, packets=[], lastSpawn=0, quality='High';
const nodeDefs=[['INTERNET',.50,.13],['GATEWAY',.50,.42],['LOCAL CORE',.50,.76],['NODE 01',.17,.52],['NODE 02',.82,.52],['NODE 03',.73,.82]];
const links=[[0,1],[1,2],[1,3],[1,4],[2,3],[2,4],[2,5],[3,0],[4,0]];

export function initializeNetwork(){canvas=document.querySelector('#networkCanvas');ctx=canvas.getContext('2d');}
export function setNetworkQuality(value){quality=value||'High'}
function resize(){const box=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,quality==='Low'?1:2),w=Math.max(2,Math.floor(box.width*dpr)),h=Math.max(2,Math.floor(box.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}return {w,h,dpr}}
export function drawNetwork(now,data){
  if(!ctx)return;const {w,h,dpr}=resize(),style=getComputedStyle(document.querySelector('#app')),primary=style.getPropertyValue('--primary').trim(),secondary=style.getPropertyValue('--secondary').trim(),primaryRgb=style.getPropertyValue('--primary-rgb').trim(),muted=style.getPropertyValue('--muted').trim(),nodeFill=style.getPropertyValue('--node-fill').trim();ctx.clearRect(0,0,w,h);
  ctx.save();ctx.strokeStyle=`rgba(${primaryRgb},.08)`;ctx.lineWidth=dpr;for(let i=1;i<7;i++){ctx.beginPath();ctx.ellipse(w/2,h*.52,w*i/13,h*i/11,0,0,Math.PI*2);ctx.stroke()}for(let i=0;i<9;i++){ctx.beginPath();ctx.moveTo(w/2,h*.52);const a=i/9*Math.PI*2;ctx.lineTo(w/2+Math.cos(a)*w*.55,h*.52+Math.sin(a)*h*.6);ctx.stroke()}
  const nodes=nodeDefs.map(n=>({name:n[0],x:n[1]*w,y:n[2]*h}));ctx.setLineDash([4*dpr,5*dpr]);links.forEach((link,index)=>{const a=nodes[link[0]],b=nodes[link[1]];ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=index%3?primary+'77':secondary+'88';ctx.lineWidth=.65*dpr;ctx.stroke()});ctx.setLineDash([]);
  const speed=.00012+Math.min(1,(data.network.download||0)/500)*.0002;if(now-lastSpawn>330&&(quality!=='Low'||packets.length<8)){lastSpawn=now;const link=links[Math.floor(Math.random()*links.length)];packets.push({link,t:0,speed:speed*(.7+Math.random()*.7),color:Math.random()>.28?primary:secondary})}packets=packets.filter(p=>p.t<1);for(const p of packets){p.t+=p.speed*16.7;const a=nodes[p.link[0]],b=nodes[p.link[1]],t=p.t*p.t*(3-2*p.t),x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t;ctx.beginPath();ctx.arc(x,y,2.2*dpr,0,Math.PI*2);ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=5*dpr;ctx.fill();ctx.shadowBlur=0}
  nodes.forEach((n,index)=>{const r=(index===2?8:5)*dpr;ctx.beginPath();ctx.arc(n.x,n.y,r,0,Math.PI*2);ctx.fillStyle=nodeFill;ctx.fill();ctx.strokeStyle=index===2?secondary:primary;ctx.lineWidth=1.1*dpr;ctx.stroke();ctx.beginPath();ctx.arc(n.x,n.y,r+5*dpr,0,Math.PI*2);ctx.strokeStyle=(index===2?secondary:primary)+'33';ctx.stroke();ctx.font=`${Math.max(7,7*dpr)}px Cascadia Mono, monospace`;ctx.textAlign='center';ctx.fillStyle=index===2?secondary:muted;ctx.fillText(n.name,n.x,n.y+r+11*dpr)});ctx.restore();
}
